[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doc-genai-system"
version = "1.1.4"
description = "Document Generation AI System. In build system phase!"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "opentelemetry-api==1.19.0",
    "opentelemetry-sdk==1.19.0",
    "opentelemetry-instrumentation-asgi==0.40b0",
    "opentelemetry-instrumentation-fastapi==0.40b0",
    "opentelemetry-instrumentation-requests==0.40b0",
    "opentelemetry-instrumentation-logging==0.40b0",
    "opentelemetry-exporter-jaeger==1.19.0",
    "opentelemetry-exporter-otlp-proto-grpc==1.19.0",
    "opentelemetry-exporter-prometheus==1.12.0rc1",
    "Pillow==9.5.0",
    "easyocr==1.7.0",
    "loguru==0.7.0",
    "fastapi==0.96.0",
    "uvicorn[standard]==0.22.0",
    "python-multipart==0.0.6",
    "prometheus-client==0.17.1",
    "imagehash==4.3.1",
]

[tool.setuptools.packages.find]
# Only include Python packages, exclude infrastructure directories
exclude = ["ansible*", "terraform*", "Iac*", "helm-charts*", "notebooks-and-apps*","tests*", "argo-apps", ".git", ".github", ".gitignore"]