apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertmanager.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
automountServiceAccountToken: false