apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    observability.flow: logs
    observability.component: visualization
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5601
      protocol: TCP
      name: http
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}