apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace | default "observability" }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    observability.flow: metrics
    observability.component: storage
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}