# gcp_project_id = "vital-orb-466100-c5"
# gcp_project_id = "my-k8s-projects-468908"
gcp_project_id = "vital-orb-466100-c5"
gcp_zone       = "asia-southeast1-b"
cluster_name   = "production-cluster"
# machine_type   = "e2-medium"
machine_type   = "e2-standard-4"
min_node_count = 1
max_node_count = 3
