apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-ocr-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/duymanhdoan/Doc-GenAI-System.git
    targetRevision: dev/argocd
    path: argocd/applications
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # ✅ FIXED - App-of-Apps phải tạo Applications trong argocd namespace
  
  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true 

    automated: 
      selfHeal: true 
      prune: true