apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jaeger.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
automountServiceAccountToken: false