global:
  namespace: observability

image:
  repository: gcr.io/cadvisor/cadvisor
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 60Mi
