apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
automountServiceAccountToken: false