apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/duymanhdoan/Doc-GenAI-System.git
    targetRevision: dev/argocd
    path: helm-charts/ocr-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: model-serving

  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true 

    automated: 
      selfHeal: true 
      prune: true 