apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/duymanhdoan/github-workflow-sample.git
    targetRevision: dev/iac-cd  # ✅ Chỉ định branch
    path: argo-cd/dev           # ✅ Relative path từ repo root
  
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp 

  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true 

    automated: 
      selfHeal: true 
      prune: true  
