- name: Create Compute Engine instances
  hosts: localhost
  tasks:
  - name: Bring up the first instance
    gcp_compute_instance:
      name: instance-1
      machine_type: e2-micro
      # Refer to https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts
      # or use the command `gcloud compute images list --project=ubuntu-os-cloud`
      zone: asia-southeast1-b	
      project: project_id
      auth_kind: serviceaccount
      service_account_file: ../secrets/
      disks:
        - auto_delete: true # Aute delete when destroying the VM
          boot: true # This disk is used for booting
          initialize_params:
            source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
      # Default network for this instance
      network_interfaces:
        - network:
            selfLink: global/networks/default
      state: absent # change to #absent #present to delete the instance